---
- name: ensure job docker images are present
  when: provider == "vagrant"
  sudo: yes
  command: /usr/bin/docker pull {{ item }}
  with_items:
    - "{{ mesos_consul_image }}:{{ mesos_consul_image_tag }}"
    - "{{ mantl_api_image }}:{{ mantl_api_image_tag }}"
  tags:
    - marathon
    - bootstrap

- name: create json files for jobs
  sudo: yes
  template:
    src: '{{ item }}.json.j2'
    dest: /etc/marathon/{{ item }}.json
  with_items:
    - mesos-consul
    - mantl-api
  tags:
    - marathon

- name: start jobs
  run_once: true
  sudo: yes
  command: 'curl -X PUT -d@/etc/marathon/{{ item }}.json -H "Content-Type: application/json" http://localhost:18080/v2/apps/{{ item }}'
  changed_when: false
  failed_when: "'deploymentId' not in result.stdout"
  register: result
  with_items:
    - mesos-consul
    - mantl-api
  tags:
    - marathon
