---
- hosts:  "{{ dc | default('all') }}"
  gather_facts: no
  serial: "{{ serial | default(1) }}"
  tasks:
    - name: clean yum
      become: yes
      command: yum clean all

    - name: refresh yum cache
      become: yes
      command: yum makecache

    - name: upgrade kernel package
      become: yes
      yum:
        name: kernel
        state: latest
      register: kernel

    - name: upgrade all packages
      become: yes
      yum:
        name: "*"
        state: latest

    # Rebooting during the ansible_local provisioning stage breaks Packer builds
    - name: reboot host
      become: yes
      shell: nohup bash -c "sleep 2s && reboot" &
      register: did_reboot
      when: "{{ kernel.changed and not (packer | default(false)) }}"

    - name: wait for host boot
      local_action:
        module: wait_for
        host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
        port: "{{ ansible_ssh_port | default(22) }}"
        delay: "{{ boot_wait | default(60) }}"
        timeout: "{{ boot_timeout | default(120) }}"
        state: started
      when: did_reboot.changed
